Handle arguments to tasks from run

diff --git a/mycmd/myproject/myproject-lib b/mycmd/myproject/myproject-lib
--- a/mycmd/myproject/myproject-lib
+++ b/mycmd/myproject/myproject-lib
@@ -233,7 +233,7 @@ function project.load_all_task_definition_files() {
 # --------------------------------------------------------------------------------------------------
 # Task Execution
 function project.execute_task() {
-    local -r fully_qualified_task_name="${1}"
+    local fully_qualified_task_name="${1}"
     shift
 
     local return_code=0
@@ -241,11 +241,27 @@ function project.execute_task() {
     # shellcheck disable=SC2034
     local -A task
     if ! project:task_registry.get_task "${fully_qualified_task_name}" task; then
-        mycmd.log "Task '${fully_qualified_task_name}' is not found"
+        mycmd.debug "Task '${fully_qualified_task_name}' is not found"
         return_code=1
-    else
-        project:task.execute task "${@}" || return_code="${?}"
     fi
+
+    if (($# > 0 && "${return_code}" != 0)); then
+        fully_qualified_task_name="${fully_qualified_task_name}/${1}"
+        shift
+
+        if ! project:task_registry.get_task "${fully_qualified_task_name}" task; then
+            mycmd.log "Task '${fully_qualified_task_name}' is not found"
+        else
+            return_code=0
+        fi
+    fi
+
+    if (("${return_code}" != 0)); then
+        mycmd.log "Task not found."
+        return 1
+    fi
+
+    project:task.execute task "${@}" || return_code="${?}"
 
     return "${return_code}"
 }
