Implement 0 arg myproject run

diff --git a/mycmd/myproject/myproject-lib b/mycmd/myproject/myproject-lib
--- a/mycmd/myproject/myproject-lib
+++ b/mycmd/myproject/myproject-lib
@@ -231,4 +231,24 @@ function project.load_task_definition_file() {
     fi
 }
 
+# --------------------------------------------------------------------------------------------------
+# Task Execution
+function project.execute_task() {
+    local -r fully_qualified_task_name="${1}"
+    shift
+
+    local return_code=0
+
+    # shellcheck disable=SC2034
+    local -A task
+    if ! project:task_registry.get_task "${fully_qualified_task_name}" task; then
+        mycmd.log "Task '${fully_qualified_task_name}' is not found"
+        return_code=1
+    else
+        project:task.execute task "${@}" || return_code="${?}"
+    fi
+
+    return "${return_code}"
+}
+
 mycmd.trace "The MyProject command group library has been sourced."
