Improve test coverage

diff --git a/mycmd/myproject/myproject-task-lib b/mycmd/myproject/myproject-task-lib
--- a/mycmd/myproject/myproject-task-lib
+++ b/mycmd/myproject/myproject-task-lib
@@ -234,6 +234,23 @@ function project:task_registry.list_tasks() {
         return 0
     fi
 
+    mycmd.output "The following tasks are registered:"
+
+    local -a all_tasks_namespaced_parts
+    if ! project:task_registry._get_all_task_namespaced_parts all_tasks_namespaced_parts; then
+        mycmd.log "Error getting all task namespaced parts"
+        return 1
+    fi
+
+    local task
+    for task in "${all_tasks_namespaced_parts[@]}"; do
+        mycmd.output "${task}"
+    done
+}
+
+function project:task_registry._get_all_task_namespaced_parts() {
+    local -n all_tasks_namespaced_parts_ref="${1}"
+
     local -a main_file_tasks=()
     local -a other_tasks=()
 
@@ -262,28 +279,21 @@ function project:task_registry.list_tasks() {
         fi
     done
 
-    local -a sorted_task_names=()
+    all_tasks_namespaced_parts_ref=()
 
     if (("${#main_file_tasks[@]}" > 0)); then
         # shellcheck disable=SC2034
-        readarray -t sorted_task_names < \
+        readarray -t all_tasks_namespaced_parts_ref < \
             <(printf '%s\n' "${main_file_tasks[@]}" | LC_ALL=en_US.UTF-8 sort || true)
     fi
 
     if (("${#other_tasks[@]}" > 0)); then
-        local size_so_far="${#sorted_task_names[@]}"
+        local size_so_far="${#all_tasks_namespaced_parts_ref[@]}"
 
         # shellcheck disable=SC2034
-        readarray -t -O "${size_so_far}" sorted_task_names < \
+        readarray -t -O "${size_so_far}" all_tasks_namespaced_parts_ref < \
             <(printf '%s\n' "${other_tasks[@]}" | LC_ALL=en_US.UTF-8 sort || true)
     fi
-
-    mycmd.output "The following tasks are registered:"
-
-    local task
-    for task in "${sorted_task_names[@]}"; do
-        mycmd.output "${task}"
-    done
 }
 
 function project:task.get_fully_qualified_name() {
